[package]
name = "aoc_2015"
version = "0.1.0"
authors = ["Florence Yernaux <florence.yernaux@ulb.ac.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
